In [2]:
# imports and settings
import torch

# PyTorch Tensors Excercises

**Exercise 1:**  What are the dimensions and shapes of the following tensors?

1. 7
2. [1, 2, 3]
3. [[1, 2], [3, 4]]
4. [[1, 2], [3, 4], [5, 6]]
5. [[[1, 2], [3, 4], [5, 6]]]
6. [[[1, 2], [3, 4], [5, 6]], [[10, 20], [30, 40], [50, 60]]]


Type your answers in this text cell.

--------------------------------------------------------------------------------

**Exercise 2:**  Create PyTorch Tensors for the tensors in Exercise 1 and use `shape` to check your answers to Exercise 1.

In [5]:
# code for Exercise 2

# an example (delete this example after you finish your exercises)
x = torch.tensor( [ [ 4, 6, 7] ] )
print(x)
print(x.shape)
print('\n')  # insert a blank line

tensor([[4, 6, 7]])
torch.Size([1, 3])




**Exercise 3:**  A tensor that has shape $3 \times 1 \times 2$ has a singleton dimennsion meaning the length of the the dimensions is one.  You can *squeeze* out single dimensions with `torch.squeeze`.  Create a $3 \times 1 \times 2$ tensor using the numbers 1 through 6, then squeeze out the singleton dimension to get a tensor with shape $3 \times 2$.

Display your tensor before and after squeezing.

In [21]:
# squeeze example
x = torch.tensor( [[1,2,3,4]])
print(x)
print(x.shape)
x_new = torch.squeeze(x)
print(x_new)
print(x_new.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([1, 2, 3, 4])
torch.Size([4])


In [ ]:
# your solution to Exercise 3 here

**Exercise 4.**  `torch.unsqueeze()` is useful for adding singleton dimensions (which is often useful when preparing data to send to a neural network).  Look up `torch.unsqueeze` and use it convert `x = torch.tensor([1,2,3,4,5])` into a $5 \times 1$ tensor and also a $1 \times 5$ tensor.  Be sure to label each, display the tensors, and display the shapes.

tensor(1)

**Exercise 5.** Repeat exercise 4 using `torch.reshape`.

**Exercise 6.**  PyTorch stores tensors in memory in row-major order ([read about it on Wikipedia](https://en.wikipedia.org/wiki/Row-_and_column-major_order)).  Essentially this means that the last index is incremented first, so the matrix so a 2D tensor, x, with shape $3 \times 2$ gets stored as x[0,0], x[0,1], x[1,0], x[1,1], x[2,0], x[2,1].  Notice that the last index changes first, then the next-to-last index, etc.  

`torch.reshape` iterates over the tensor elements in memory and fills them into the new shape in row-major order.

If you start with `x = torch.tensor([1,2,3,4,5,6,7,8[)` and use 'x2 = torch.reshape(x,(2,2,2))' to create a new 3D tensor from `x`.  What indices would you use to access the number 5 in `x2`?  Try to do this without code first, then verify it with code.

**Exercise 7.**  Consider the reshaped tensor in Exercise 6.  Show how to use slices to get the following tensors:

1. [[1,2],[3,4]]
2. [[5,6],[7,8]]
3. [[1,3],[5,7]]
4. [[2,4],[6,8]]
5. [5,6]
6. [5,7]

Try to do this by thinking before trying random permuations :)

Start with the tensor `x` in the next cell and use print to show the various slices.

In [28]:
x = torch.reshape( torch.tensor( [1,2,3,4,5,6,7,8]),(2,2,2))

print(x[:,0,1]) #example

tensor([2, 6])


**Exercise 8.**  Show how to use `torch.transpose` to transpose the 2D tensor [[1,2],[3,4]] to [[1,3],[2,4]].

**Exercise 9.**  `torch.tranpose` can be used to swap any two dimensions a tensor.  Show how to transpose the tensor

[[[1, 2], [3, 4], [5, 6]], [[10, 20], [30, 40], [50, 60]]]

to

[[[1, 3, 5], [2,  4,  6]], [[10, 30, 50], [20, 40, 60]]]

in PyTorch.

**Exercise 10.**  Demonstrate how to do matrix-vector multiplication in PyTorch. Give an example where the matrix is $2 \times 3$ multiplies a vector of appropriate length.

**Exercise 11.**  Show how to compute the dot procduct of two vectors in PyTorch.  Give an example where each of the vectors has length 3.  This should give you a 0-dimensional tensor.  Also show how to get just the number from the tensor result.

**Exercise 12.**  PyTorch uses *broadcasting* to perform operations on tensors of different shapes without explicitly resizing or reshaping them.  (ChatGPT gives a great response to the prompt 'explain how broadcasting works in pytorch'.)

Starting the matrix A = [ [1, 2], [3, 4] ] show how, using broadcasting, to:

1.  Add 7 to each element in A.
2.  Add [5,10] to each row in A.
3.  Add [5,10] to each column in A.

Your code in the next cell should print out all the results:

Exercise 13.  Show how to produce a $3 \times 4$ tensor full of sevens two different ways:

1.  use `torch.full`
2.  use `torch.ones` and broadcasting